version: '3'

services:
  c2:
    container_name: gathering_backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - 8885:8885
    volumes:
      - ./backend/.:/backend

  ui:
    container_name: gathering_ui
    build:
      context: .
      dockerfile: ui/Dockerfile.dev
    ports:
      - "3003:3000"
    volumes:
      - ./ui/.:/ui
    environment:
      - REACT_APP_API_URL=http://181.214.140.145:8885
  
  
