# Use an official Node.js image as the base image
FROM node:latest

# Set the working directory in the container
WORKDIR /ui

# Copy package.json and package-lock.json to the working directory
COPY ui/package*.json ./

# RUN rm -rf node_modules
# RUN rm -rf package-json.lock
# Install dependencies
RUN cd /ui

RUN npm install --force

RUN npm install react-scripts --force

# Copy the entire project to the working directory
COPY . .

# Expose the port the app runs on
EXPOSE 3000

# Start the React app
CMD ["npm","start"]
